name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

env:
  TC_CLOUD_TOKEN: $

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup dotnet 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.100'
    - name: Prepare Testcontainers Cloud agent
      if: env.TC_CLOUD_TOKEN != ''
      uses: atomicjar/testcontainers-cloud-setup-action@main
    - name: Build and Test
      run: ./Build.ps1
      shell: pwsh
    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: artifacts/**/*
